"""Per-iteration parity test for NNI port (Layer 3 step 3/3, spsolve branch).

Single test case: NNI Q7 (= Multi Q5 / HONI Q4 same AA + initial_vector, rng(42)).
Loads matlab_ref/nni/nni_reference.mat (generated by generate_nni_reference.m).

Tier design (revised after pattern-C diagnosis, Session 4 Z1):

  Tier 1 STRICT — 逐 iter bit-identical (overlap slots [0:K_common])
      - ABS tol 1e-10:
          lambda_U_history, lambda_L_history, res_history (1-D)
          x_history, w_history (2-D)
          chit_history, hit_per_outer_history (≡0 both sides)
      - REL tol 1e-10:
          y_history[:, 1:K_common]  (linear solve output; slot 0 is init NaN)

  Tier 2 APPROX — final outputs (algorithmic equivalence)
      - lambda_U: abs diff ≤ 1e-12 (tol range; final λ converges to noise floor)
      - x:        rel diff ≤ 1e-8  (unit-norm eigenvector, should stay close)
      - 兩邊可能停在不同 iter (MATLAB/Python 用不同浮點路徑、同 tol 觸發時機不同)

  Tier 3 INFORMATIONAL (no assert)
      - nit scalar (MATLAB 1-based vs Python+1)
      - MATLAB 多出的 iters (Python 已停後、MATLAB 繼續震盪的那幾 iter)
        印 res 值展示 noise-floor 震盪

PASS condition: Tier 1 + Tier 2 全過。

Why this tier design (pattern-C 根因):
  診斷 iter 18-21 顯示 x/w/y 逐欄 diff 在 machine epsilon (~1e-15)，linear solve
  兩邊 bit-identical。但 `temp = tpv(AA, x, m) / (x^(m-1))` 的 element-wise
  除法在 min(x_i) ~ 4.8e-6 時把 tpv 的 1e-16 誤差放大到 ~1e-12、和 tol=1e-12
  同量級、造成 res 停止條件的抽籤（Python iter 21 res=1.1e-14 過 tol、
  MATLAB iter 21 res=1.3e-12 未過、繼續跑到 iter 26）。
  這是 Rayleigh-quotient 類演算法（λ = max(AAx^(m-1) / x^(m-1))）的通用現象、
  不是 Q11 的 sparse-vs-dense LU pivot 差異、不是 port bug。
"""
from pathlib import Path

import numpy as np
from scipy.io import loadmat
from scipy.sparse import issparse

from poc_iteration import find_divergence, print_neighborhood, report
from tensor_utils import nni

REF_DIR = Path(__file__).resolve().parent.parent / "matlab_ref" / "nni"

# Tier thresholds
TIER1_ABS = 1e-10            # Tier 1 STRICT ABS — per-iter history overlap slots
TIER1_Y_RTOL = 1e-10         # Tier 1 STRICT REL — y_history (linear solve output)
TIER2_LAMBDA_ABS = 1e-12     # Tier 2 APPROX — final lambda (tol range)
TIER2_X_RTOL = 1e-8          # Tier 2 APPROX — final x (eigenvector rel diff)


def _per_iter_max_abs_diff(ml_2d, py_2d):
    """(n, K) history → (K,) per-iter max|diff|, NaN-safe."""
    diff = ml_2d - py_2d
    diff = np.where(np.isnan(diff), 0.0, diff)
    return np.max(np.abs(diff), axis=0)


def _per_iter_max_magnitude(ml_2d):
    """(n, K) → (K,) per-iter max|ml|, NaN-safe."""
    ml_safe = np.where(np.isnan(ml_2d), 0.0, ml_2d)
    return np.max(np.abs(ml_safe), axis=0)


def _compare_2d(ml_2d, py_2d, tolerance, name):
    """find_divergence for 2-D history via per-iter max ABS diff."""
    per_iter = _per_iter_max_abs_diff(ml_2d, py_2d)
    return find_divergence(per_iter, np.zeros_like(per_iter), tolerance, name)


def _compare_2d_relative(ml_2d, py_2d, rtol, name):
    """find_divergence for 2-D history via per-iter max REL diff."""
    per_iter_abs = _per_iter_max_abs_diff(ml_2d, py_2d)
    per_iter_mag = _per_iter_max_magnitude(ml_2d)
    per_iter_rel = per_iter_abs / np.maximum(per_iter_mag, 1e-300)
    return find_divergence(per_iter_rel, np.zeros_like(per_iter_rel), rtol, name)


def _print_tier_header(K_ml, K_py, K_common):
    print(
        f"\nTier semantics (K_ml={K_ml}, K_py={K_py}, K_common={K_common}):\n"
        f"  Tier 1 STRICT — overlap slots [0:{K_common}]:\n"
        f"    ABS tol {TIER1_ABS:.0e}:\n"
        f"      - x_history, w_history                              (2-D)\n"
        f"      - lambda_U_history, lambda_L_history, res_history   (1-D)\n"
        f"      - chit_history, hit_per_outer_history                (≡0 both sides)\n"
        f"    REL tol {TIER1_Y_RTOL:.0e}:\n"
        f"      - y_history[:, 1:{K_common}]  (linear solve output, slot 0 NaN init)\n"
        f"  Tier 2 APPROX — final outputs (algorithmic equivalence):\n"
        f"      - final lambda_U  ABS tol {TIER2_LAMBDA_ABS:.0e}\n"
        f"      - final x         REL tol {TIER2_X_RTOL:.0e}\n"
        f"  Tier 3 INFORMATIONAL (no-assert):\n"
        f"      - nit scalars (MATLAB 1-based vs Python+1)\n"
        f"      - MATLAB's extra iters beyond K_common (noise-floor oscillation)\n"
        f"  PASS = Tier 1 + Tier 2 全過; Tier 3 prints info only."
    )


def test_nni_parity_spsolve():
    ref_path = REF_DIR / "nni_reference.mat"
    if not ref_path.exists():
        raise FileNotFoundError(
            f"{ref_path} not found. Run matlab_ref/nni/generate_nni_reference.m "
            "in MATLAB first."
        )

    data = loadmat(str(ref_path), squeeze_me=True)

    # --- Inputs ---
    AA = data["AA"]
    m = int(data["m"])
    tol = float(data["tol"])
    maxit = int(data["maxit"])
    initial_vector = np.asarray(data["initial_vector"], dtype=np.float64).ravel()

    n = AA.shape[0]
    print(
        f"Loaded nni_reference.mat: "
        f"AA {'sparse' if issparse(AA) else 'dense'} {AA.shape} "
        f"nnz={AA.nnz if issparse(AA) else '-'}, "
        f"m={m}, tol={tol:.0e}, maxit={maxit}"
    )

    # --- MATLAB outputs ---
    x_ml        = np.asarray(data["x"], dtype=np.float64).ravel()
    lambda_ml   = float(data["lambda"])
    lambda_L_ml = float(data["lambda_L"])
    res_ml      = np.asarray(data["res"], dtype=np.float64).ravel()
    nit_ml      = int(data["nit"])
    chit_ml     = int(data["chit"])

    x_history_ml             = np.asarray(data["x_history"], dtype=np.float64)
    lambda_U_history_ml      = np.asarray(data["lambda_U_history"], dtype=np.float64).ravel()
    lambda_L_history_ml      = np.asarray(data["lambda_L_history"], dtype=np.float64).ravel()
    w_history_ml             = np.asarray(data["w_history"], dtype=np.float64)
    y_history_ml             = np.asarray(data["y_history"], dtype=np.float64)
    chit_history_ml          = np.asarray(data["chit_history"], dtype=np.float64).ravel()
    hit_per_outer_history_ml = np.asarray(data["hit_per_outer_history"], dtype=np.float64).ravel()

    print(f"MATLAB: nit={nit_ml} (1-based → K_ml = nit = {nit_ml})")
    print(f"        chit={chit_ml} (canonical: must be 0)")
    print(f"        lambda_U={lambda_ml:.15e}")
    print(f"        lambda_L={lambda_L_ml:.15e}")

    # --- Run Python NNI with record_history=True, spsolve branch ---
    lambda_py, x_py, nit_py, lambda_L_py, res_py, lambda_U_hist_py, history_py = nni(
        AA, m, tol,
        linear_solver="spsolve",
        initial_vector=initial_vector,
        maxit=maxit,
        record_history=True,
        matlab_compat=True,
    )
    print(
        f"Python: nit={nit_py} (0-based → K_py = nit+1 = {nit_py + 1}), "
        f"lambda_U={lambda_py:.15e}, lambda_L={lambda_L_py:.15e}"
    )

    K_ml = nit_ml                # MATLAB history length (1-based nit)
    K_py = nit_py + 1            # Python history length (0-based nit + 1)
    K_common = min(K_ml, K_py)   # overlap range [0:K_common]

    # --- Shape sanity (full history arrays, not truncated) ---
    shape_checks = [
        (x_history_ml, history_py["x_history"], n, "x_history"),
        (lambda_U_history_ml, history_py["lambda_U_history"], None, "lambda_U_history"),
        (lambda_L_history_ml, history_py["lambda_L_history"], None, "lambda_L_history"),
        (res_ml, res_py, None, "res_history"),
        (w_history_ml, history_py["w_history"], n, "w_history"),
        (y_history_ml, history_py["y_history"], n, "y_history"),
        (chit_history_ml, history_py["chit_history"], None, "chit_history"),
        (hit_per_outer_history_ml, history_py["hit_per_outer_history"], None, "hit_per_outer_history"),
    ]
    for ml_arr, py_arr, leading_n, name in shape_checks:
        if leading_n is not None:
            expected_ml = (leading_n, K_ml)
            expected_py = (leading_n, K_py)
        else:
            expected_ml = (K_ml,)
            expected_py = (K_py,)
        if ml_arr.shape != expected_ml:
            raise AssertionError(
                f"{name} MATLAB shape {ml_arr.shape} != expected {expected_ml}"
            )
        if py_arr.shape != expected_py:
            raise AssertionError(
                f"{name} Python shape {py_arr.shape} != expected {expected_py}"
            )

    _print_tier_header(K_ml, K_py, K_common)

    # ============================================================
    # Tier 1: STRICT — overlap slots [0:K_common]
    # ============================================================
    print(f"\n=== Tier 1 STRICT (overlap [0:{K_common}]) ===")
    tier1_fails = []

    # --- 1a: 1-D fields, ABS ---
    for ml, py, name in [
        (lambda_U_history_ml, history_py["lambda_U_history"], "lambda_U_history"),
        (lambda_L_history_ml, history_py["lambda_L_history"], "lambda_L_history"),
        (res_ml, res_py, "res_history"),
        (chit_history_ml, history_py["chit_history"], "chit_history"),
        (hit_per_outer_history_ml, history_py["hit_per_outer_history"], "hit_per_outer_history"),
    ]:
        r = find_divergence(ml[:K_common], py[:K_common], TIER1_ABS, name)
        report(r)
        if not r["passed"]:
            tier1_fails.append((name, r, ml, py))

    # --- 1b: 2-D fields, ABS ---
    for ml_2d, py_2d, name in [
        (x_history_ml, history_py["x_history"], "x_history (2D)"),
        (w_history_ml, history_py["w_history"], "w_history (2D)"),
    ]:
        r = _compare_2d(ml_2d[:, :K_common], py_2d[:, :K_common], TIER1_ABS, name)
        report(r)
        if not r["passed"]:
            tier1_fails.append((name, r, None, None))

    # --- 1c: y_history REL, slots [1:K_common] (slot 0 NaN init both sides) ---
    if K_common >= 2:
        r = _compare_2d_relative(
            y_history_ml[:, 1:K_common],
            history_py["y_history"][:, 1:K_common],
            TIER1_Y_RTOL,
            f"y_history[:, 1:{K_common}] (REL)",
        )
        report(r)
        if not r["passed"]:
            tier1_fails.append(("y_history", r, None, None))

    # ============================================================
    # Tier 2: APPROX — final outputs (algorithmic equivalence)
    # ============================================================
    print(f"\n=== Tier 2 APPROX — final outputs ===")
    tier2_fails = []

    lambda_diff = abs(lambda_ml - lambda_py)
    lambda_pass = lambda_diff <= TIER2_LAMBDA_ABS
    print(
        f"  [final lambda_U] {'PASS' if lambda_pass else 'FAIL'}  "
        f"|λ_ml - λ_py| = {lambda_diff:.3e}  (tol {TIER2_LAMBDA_ABS:.0e})"
    )
    if not lambda_pass:
        tier2_fails.append("final lambda_U")

    x_diff_abs = float(np.linalg.norm(x_ml - x_py))
    x_norm_ml = float(np.linalg.norm(x_ml))
    x_rel = x_diff_abs / max(x_norm_ml, 1e-300)
    x_pass = x_rel <= TIER2_X_RTOL
    print(
        f"  [final x]        {'PASS' if x_pass else 'FAIL'}  "
        f"||x_ml - x_py|| / ||x_ml|| = {x_rel:.3e}  (rtol {TIER2_X_RTOL:.0e})"
    )
    if not x_pass:
        tier2_fails.append("final x")

    # ============================================================
    # Tier 3: INFORMATIONAL — no assert
    # ============================================================
    print(f"\n=== Tier 3 INFORMATIONAL (no-assert) ===")
    nit_match = (nit_ml == nit_py + 1)
    print(
        f"  nit: MATLAB={nit_ml}, Python+1={nit_py + 1}  "
        f"{'MATCH' if nit_match else 'DIFF (expected — floating-point lottery)'}"
    )
    print(
        f"  chit: MATLAB={chit_ml}, Python=0  "
        f"{'(canonical halving disabled, both ≡ 0)' if chit_ml == 0 else '(unexpected)'}"
    )
    if K_ml > K_common:
        print(
            f"\n  MATLAB 多出 {K_ml - K_common} iter (Python 已於 iter {K_common - 1} 停止):"
        )
        for k in range(K_common, K_ml):
            print(
                f"    iter {k}: λ_U={lambda_U_history_ml[k]:.15e}  "
                f"res={res_ml[k]:.3e}  λ_L={lambda_L_history_ml[k]:.15e}"
            )
        print(
            f"  Note: Both branches reach noise floor (~{TIER2_LAMBDA_ABS:.0e}); "
            f"stopping iter depends on\n"
            f"  floating-point lottery (res crossing tol={tol:.0e}), not algorithmic difference.\n"
            f"  Root cause: `temp = tpv/x^(m-1)` amplifies ~1e-16 rounding by ~1/min(x)^(m-1)\n"
            f"  (min(x_i) ~ 4.8e-6 → amplification ~4e10 → temp diff ~1e-12 ~ tol)."
        )
    elif K_py > K_common:
        print(f"\n  Python 多出 {K_py - K_common} iter (MATLAB 已停)：unusual; investigate.")

    # ============================================================
    # Final pass/fail
    # ============================================================
    if tier1_fails or tier2_fails:
        print(f"\n=== FAIL ===")
        print(f"  Tier 1 failures: {len(tier1_fails)}")
        print(f"  Tier 2 failures: {len(tier2_fails)}")
        # Neighborhood for any 1-D Tier 1 failure
        for name, r, ml_full, py_full in tier1_fails:
            if isinstance(r, dict) and r.get("first_bad_iter") is not None and ml_full is not None:
                print_neighborhood(ml_full, py_full, r["first_bad_iter"], 2, name)
        raise AssertionError("NNI parity FAILED at Tier 1 or Tier 2")

    print(f"\n=== PASS ===")
    print(
        f"  Tier 1 STRICT: all {K_common} overlap slots within abs {TIER1_ABS:.0e} "
        f"/ y_history within rel {TIER1_Y_RTOL:.0e}"
    )
    print(
        f"  Tier 2 APPROX: final λ abs {lambda_diff:.3e} ≤ {TIER2_LAMBDA_ABS:.0e}; "
        f"final x rel {x_rel:.3e} ≤ {TIER2_X_RTOL:.0e}"
    )
    if K_ml > K_common:
        print(
            f"  Tier 3 INFO  : MATLAB iter {K_common}..{K_ml - 1} are noise-floor "
            f"oscillation, Python stopped earlier (documented above)"
        )


if __name__ == "__main__":
    print("=" * 70)
    print("NNI parity — spsolve branch (Q7 case, Multi Q5 / HONI Q4 same AA)")
    print("=" * 70)
    test_nni_parity_spsolve()
